### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by jazzz** [LumenFactory/arc-game#1]
@matthewbeck the First steps are to get the tools installed on your computer so you can push code to the micro controller

You can find the steps in the [readme](https://github.com/LumenFactory/arc-game).

- [x] Install Tools
- [x] upload blink Sketch
- [x] upload mainhub sketch

**Comment by matthewbeck** [comment]
@jazzz was able to successfully upload all three. Main question I have at this point is the setup messages are not being printed before the update_game loop is run (see lines 43 and 50)

**Comment by jazzz** [comment]
@matthewbeck if it's just the print statements in the setup function you can try increasing the delay on line 36 from 100 to 1000. 

to be sure everything is updating correctly, you can changing one of the statements you are seeing in the Serial monitor to make sure it is updating. 

Most important part here is to make sure that code is updating when you press  upload and you can see the new channges

**Comment by jazzz** [comment]
Closing this as it seems @matthewbeck is already up and running with #4 🚀
