### ISSUE TITLE
Basic game tasks 

### ISSUE THREAD

**Issue by matthewbeck** [LumenFactory/arc-game#3]
List of tasks that I will complete as I work through adding complexity to the game

- [x] add space bar logic to existing arc text game (if space bar press and cursor value is = target_index +- target width, then print "success", else print "fail"
- [x] create level 2  same loop as level one, but the wait_update is decreased to 100
- [x] build game logic that if level 1 fail, run loop again from level 1, if success, run level 2
- [x] create successive levels 2-8 with incrementally decreasing wait_update times
- [x] decrease target range for each successive level from 1-8
- [x] build on test led strip (23 leds)
- [x] change colors for each successive level;
- [x] create "bounce effect" where cursor_index increases from min (0) and decreases from max repeatedly
- [x] add win animation
- [x] add loss animation

**Comment by jazzz** [comment]
@matthewbeck 
SpaceBar logic will be difficult with the serial monitor.

the following code listens for 'any character' + enter and then toggles the button. 
https://github.com/LumenFactory/arc-game/blob/main/mainhub/mainhub.ino#L52-L56

for testing you should be able to type 'a'+enter into the Serial monitor text input and the LED on the micro controller will go off

**Comment by jazzz** [comment]
@matthewbeck 

looks like you are getting ready to start looking at lights and stuff.

You'll want to use the fastLed library. (its not necessary, but very helpful)

Setup Instructions: https://www.ardu-badge.com/FastLED
Example: Look at combining the Examples->FastLed->Blink example with the following code snippet

```
void fill_color(uint8_t hue){
  for (int i=0;i< NUM_LEDS;i++){
      leds[i] = CHSV(hue,255, 255);
  }
  FastLED.show();
}
```

**Comment by matthewbeck** [comment]
@jazzz getting this error when trying to run the Blink sketch - any thoughts on why that might be?

No connection established

Compilation error: No connection established

**Comment by matthewbeck** [comment]
Completed these "basic" tasks to get a very simple, but playable game up and ready. Spinning up a new task list for the more complex items we'd like to add to the game to make it play better

**Comment by jazzz** [comment]
@matthewbeck this is looking done! feel free to close the issue if there is no more work left -- You've earned it!
